printfn "%f" (abs 2.0)
printfn "%f" (abs 0.0)
printfn "%f" (exp 0.0)
printfn "%f" (log 1.0)
printfn "%f" (log 2.0)
printfn "%f" (log10 0.001)
printfn "%f" (sqrt 2.0)
printfn "%f" (sqrt 3.0)
let pi = acos -1.0
printfn "%f" pi
printfn "%f" (sin 0.0)
printfn "%f" (sin pi / 2.0)
printfn "%f" (tan 0.0)
printfn "%f" (tan pi)
printfn "%f" (atan 1.0)
printfn "%f" (acos -1.0)
printfn "%f" (atan2 0.0 -1.0)
printfn "%f" (sinh 1.0)
printfn "%f" (cosh 1.0)
printfn "%f" (tanh 1.0)
printfn "%f" (ceil 2.3)
printfn "%f" (ceil 2.6)
printfn "%f" (floor 2.3)
printfn "%f" (floor 2.6)
printfn "%f" (round 2.3)
printfn "%f" (round 2.6)
printfn "%f" (2.0 ** 3.0)
printfn "%f" (2.0 ** 0.5)
printfn "%i" (pown 2 3)
printfn "%i" (pown 2 0)
